// Code generated by protoc-gen-go. DO NOT EDIT.
// source: appstore.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestHeader_Platform int32

const (
	RequestHeader_WIN32_X86      RequestHeader_Platform = 0
	RequestHeader_OSX_X86        RequestHeader_Platform = 1
	RequestHeader_LINUX_X86      RequestHeader_Platform = 2
	RequestHeader_IPHONE_ARM     RequestHeader_Platform = 3
	RequestHeader_SYMBIANS60_ARM RequestHeader_Platform = 4
	RequestHeader_OSX_POWERPC    RequestHeader_Platform = 5
	RequestHeader_ANDROID_ARM    RequestHeader_Platform = 6
	RequestHeader_WINCE_ARM      RequestHeader_Platform = 7
	RequestHeader_LINUX_X86_64   RequestHeader_Platform = 8
	RequestHeader_OSX_X86_64     RequestHeader_Platform = 9
	RequestHeader_PALM_ARM       RequestHeader_Platform = 10
	RequestHeader_LINUX_SH       RequestHeader_Platform = 11
	RequestHeader_FREEBSD_X86    RequestHeader_Platform = 12
	RequestHeader_FREEBSD_X86_64 RequestHeader_Platform = 13
	RequestHeader_BLACKBERRY_ARM RequestHeader_Platform = 14
	RequestHeader_SONOS_UNKNOWN  RequestHeader_Platform = 15
	RequestHeader_LINUX_MIPS     RequestHeader_Platform = 16
	RequestHeader_LINUX_ARM      RequestHeader_Platform = 17
	RequestHeader_LOGITECH_ARM   RequestHeader_Platform = 18
	RequestHeader_LINUX_BLACKFIN RequestHeader_Platform = 19
	RequestHeader_ONKYO_ARM      RequestHeader_Platform = 21
	RequestHeader_QNXNTO_ARM     RequestHeader_Platform = 22
	RequestHeader_BADPLATFORM    RequestHeader_Platform = 255
)

var RequestHeader_Platform_name = map[int32]string{
	0:   "WIN32_X86",
	1:   "OSX_X86",
	2:   "LINUX_X86",
	3:   "IPHONE_ARM",
	4:   "SYMBIANS60_ARM",
	5:   "OSX_POWERPC",
	6:   "ANDROID_ARM",
	7:   "WINCE_ARM",
	8:   "LINUX_X86_64",
	9:   "OSX_X86_64",
	10:  "PALM_ARM",
	11:  "LINUX_SH",
	12:  "FREEBSD_X86",
	13:  "FREEBSD_X86_64",
	14:  "BLACKBERRY_ARM",
	15:  "SONOS_UNKNOWN",
	16:  "LINUX_MIPS",
	17:  "LINUX_ARM",
	18:  "LOGITECH_ARM",
	19:  "LINUX_BLACKFIN",
	21:  "ONKYO_ARM",
	22:  "QNXNTO_ARM",
	255: "BADPLATFORM",
}

var RequestHeader_Platform_value = map[string]int32{
	"WIN32_X86":      0,
	"OSX_X86":        1,
	"LINUX_X86":      2,
	"IPHONE_ARM":     3,
	"SYMBIANS60_ARM": 4,
	"OSX_POWERPC":    5,
	"ANDROID_ARM":    6,
	"WINCE_ARM":      7,
	"LINUX_X86_64":   8,
	"OSX_X86_64":     9,
	"PALM_ARM":       10,
	"LINUX_SH":       11,
	"FREEBSD_X86":    12,
	"FREEBSD_X86_64": 13,
	"BLACKBERRY_ARM": 14,
	"SONOS_UNKNOWN":  15,
	"LINUX_MIPS":     16,
	"LINUX_ARM":      17,
	"LOGITECH_ARM":   18,
	"LINUX_BLACKFIN": 19,
	"ONKYO_ARM":      21,
	"QNXNTO_ARM":     22,
	"BADPLATFORM":    255,
}

func (x RequestHeader_Platform) Enum() *RequestHeader_Platform {
	p := new(RequestHeader_Platform)
	*p = x
	return p
}

func (x RequestHeader_Platform) String() string {
	return proto.EnumName(RequestHeader_Platform_name, int32(x))
}

func (x *RequestHeader_Platform) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RequestHeader_Platform_value, data, "RequestHeader_Platform")
	if err != nil {
		return err
	}
	*x = RequestHeader_Platform(value)
	return nil
}

func (RequestHeader_Platform) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_de00bd9912617d1d, []int{3, 0}
}

type RequestHeader_DeviceClass int32

const (
	RequestHeader_DESKTOP RequestHeader_DeviceClass = 1
	RequestHeader_TABLET  RequestHeader_DeviceClass = 2
	RequestHeader_MOBILE  RequestHeader_DeviceClass = 3
	RequestHeader_WEB     RequestHeader_DeviceClass = 4
	RequestHeader_TV      RequestHeader_DeviceClass = 5
)

var RequestHeader_DeviceClass_name = map[int32]string{
	1: "DESKTOP",
	2: "TABLET",
	3: "MOBILE",
	4: "WEB",
	5: "TV",
}

var RequestHeader_DeviceClass_value = map[string]int32{
	"DESKTOP": 1,
	"TABLET":  2,
	"MOBILE":  3,
	"WEB":     4,
	"TV":      5,
}

func (x RequestHeader_DeviceClass) Enum() *RequestHeader_DeviceClass {
	p := new(RequestHeader_DeviceClass)
	*p = x
	return p
}

func (x RequestHeader_DeviceClass) String() string {
	return proto.EnumName(RequestHeader_DeviceClass_name, int32(x))
}

func (x *RequestHeader_DeviceClass) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RequestHeader_DeviceClass_value, data, "RequestHeader_DeviceClass")
	if err != nil {
		return err
	}
	*x = RequestHeader_DeviceClass(value)
	return nil
}

func (RequestHeader_DeviceClass) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_de00bd9912617d1d, []int{3, 1}
}

type AppItem_Requirement int32

const (
	AppItem_REQUIRED_INSTALL AppItem_Requirement = 1
	AppItem_LAZYLOAD         AppItem_Requirement = 2
	AppItem_OPTIONAL_INSTALL AppItem_Requirement = 3
)

var AppItem_Requirement_name = map[int32]string{
	1: "REQUIRED_INSTALL",
	2: "LAZYLOAD",
	3: "OPTIONAL_INSTALL",
}

var AppItem_Requirement_value = map[string]int32{
	"REQUIRED_INSTALL": 1,
	"LAZYLOAD":         2,
	"OPTIONAL_INSTALL": 3,
}

func (x AppItem_Requirement) Enum() *AppItem_Requirement {
	p := new(AppItem_Requirement)
	*p = x
	return p
}

func (x AppItem_Requirement) String() string {
	return proto.EnumName(AppItem_Requirement_name, int32(x))
}

func (x *AppItem_Requirement) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AppItem_Requirement_value, data, "AppItem_Requirement")
	if err != nil {
		return err
	}
	*x = AppItem_Requirement(value)
	return nil
}

func (AppItem_Requirement) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_de00bd9912617d1d, []int{4, 0}
}

type AppItem_Type int32

const (
	AppItem_APPLICATION AppItem_Type = 0
	AppItem_FRAMEWORK   AppItem_Type = 1
	AppItem_BRIDGE      AppItem_Type = 2
)

var AppItem_Type_name = map[int32]string{
	0: "APPLICATION",
	1: "FRAMEWORK",
	2: "BRIDGE",
}

var AppItem_Type_value = map[string]int32{
	"APPLICATION": 0,
	"FRAMEWORK":   1,
	"BRIDGE":      2,
}

func (x AppItem_Type) Enum() *AppItem_Type {
	p := new(AppItem_Type)
	*p = x
	return p
}

func (x AppItem_Type) String() string {
	return proto.EnumName(AppItem_Type_name, int32(x))
}

func (x *AppItem_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AppItem_Type_value, data, "AppItem_Type")
	if err != nil {
		return err
	}
	*x = AppItem_Type(value)
	return nil
}

func (AppItem_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_de00bd9912617d1d, []int{4, 1}
}

type AppInfo struct {
	Identifier           *string  `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
	VersionInt           *int32   `protobuf:"varint,2,opt,name=version_int,json=versionInt" json:"version_int,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppInfo) Reset()         { *m = AppInfo{} }
func (m *AppInfo) String() string { return proto.CompactTextString(m) }
func (*AppInfo) ProtoMessage()    {}
func (*AppInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_de00bd9912617d1d, []int{0}
}

func (m *AppInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppInfo.Unmarshal(m, b)
}
func (m *AppInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppInfo.Marshal(b, m, deterministic)
}
func (m *AppInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppInfo.Merge(m, src)
}
func (m *AppInfo) XXX_Size() int {
	return xxx_messageInfo_AppInfo.Size(m)
}
func (m *AppInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AppInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AppInfo proto.InternalMessageInfo

func (m *AppInfo) GetIdentifier() string {
	if m != nil && m.Identifier != nil {
		return *m.Identifier
	}
	return ""
}

func (m *AppInfo) GetVersionInt() int32 {
	if m != nil && m.VersionInt != nil {
		return *m.VersionInt
	}
	return 0
}

type AppInfoList struct {
	Items                []*AppInfo `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AppInfoList) Reset()         { *m = AppInfoList{} }
func (m *AppInfoList) String() string { return proto.CompactTextString(m) }
func (*AppInfoList) ProtoMessage()    {}
func (*AppInfoList) Descriptor() ([]byte, []int) {
	return fileDescriptor_de00bd9912617d1d, []int{1}
}

func (m *AppInfoList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppInfoList.Unmarshal(m, b)
}
func (m *AppInfoList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppInfoList.Marshal(b, m, deterministic)
}
func (m *AppInfoList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppInfoList.Merge(m, src)
}
func (m *AppInfoList) XXX_Size() int {
	return xxx_messageInfo_AppInfoList.Size(m)
}
func (m *AppInfoList) XXX_DiscardUnknown() {
	xxx_messageInfo_AppInfoList.DiscardUnknown(m)
}

var xxx_messageInfo_AppInfoList proto.InternalMessageInfo

func (m *AppInfoList) GetItems() []*AppInfo {
	if m != nil {
		return m.Items
	}
	return nil
}

type SemanticVersion struct {
	Major                *int32   `protobuf:"varint,1,opt,name=major" json:"major,omitempty"`
	Minor                *int32   `protobuf:"varint,2,opt,name=minor" json:"minor,omitempty"`
	Patch                *int32   `protobuf:"varint,3,opt,name=patch" json:"patch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SemanticVersion) Reset()         { *m = SemanticVersion{} }
func (m *SemanticVersion) String() string { return proto.CompactTextString(m) }
func (*SemanticVersion) ProtoMessage()    {}
func (*SemanticVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_de00bd9912617d1d, []int{2}
}

func (m *SemanticVersion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SemanticVersion.Unmarshal(m, b)
}
func (m *SemanticVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SemanticVersion.Marshal(b, m, deterministic)
}
func (m *SemanticVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SemanticVersion.Merge(m, src)
}
func (m *SemanticVersion) XXX_Size() int {
	return xxx_messageInfo_SemanticVersion.Size(m)
}
func (m *SemanticVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_SemanticVersion.DiscardUnknown(m)
}

var xxx_messageInfo_SemanticVersion proto.InternalMessageInfo

func (m *SemanticVersion) GetMajor() int32 {
	if m != nil && m.Major != nil {
		return *m.Major
	}
	return 0
}

func (m *SemanticVersion) GetMinor() int32 {
	if m != nil && m.Minor != nil {
		return *m.Minor
	}
	return 0
}

func (m *SemanticVersion) GetPatch() int32 {
	if m != nil && m.Patch != nil {
		return *m.Patch
	}
	return 0
}

type RequestHeader struct {
	Market               *string                    `protobuf:"bytes,1,opt,name=market" json:"market,omitempty"`
	Platform             *RequestHeader_Platform    `protobuf:"varint,2,opt,name=platform,enum=proto.RequestHeader_Platform" json:"platform,omitempty"`
	AppInfos             *AppInfoList               `protobuf:"bytes,6,opt,name=app_infos,json=appInfos" json:"app_infos,omitempty"`
	BridgeIdentifier     *string                    `protobuf:"bytes,7,opt,name=bridge_identifier,json=bridgeIdentifier" json:"bridge_identifier,omitempty"`
	BridgeVersion        *SemanticVersion           `protobuf:"bytes,8,opt,name=bridge_version,json=bridgeVersion" json:"bridge_version,omitempty"`
	DeviceClass          *RequestHeader_DeviceClass `protobuf:"varint,9,opt,name=device_class,json=deviceClass,enum=proto.RequestHeader_DeviceClass" json:"device_class,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *RequestHeader) Reset()         { *m = RequestHeader{} }
func (m *RequestHeader) String() string { return proto.CompactTextString(m) }
func (*RequestHeader) ProtoMessage()    {}
func (*RequestHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_de00bd9912617d1d, []int{3}
}

func (m *RequestHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestHeader.Unmarshal(m, b)
}
func (m *RequestHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestHeader.Marshal(b, m, deterministic)
}
func (m *RequestHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestHeader.Merge(m, src)
}
func (m *RequestHeader) XXX_Size() int {
	return xxx_messageInfo_RequestHeader.Size(m)
}
func (m *RequestHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestHeader.DiscardUnknown(m)
}

var xxx_messageInfo_RequestHeader proto.InternalMessageInfo

func (m *RequestHeader) GetMarket() string {
	if m != nil && m.Market != nil {
		return *m.Market
	}
	return ""
}

func (m *RequestHeader) GetPlatform() RequestHeader_Platform {
	if m != nil && m.Platform != nil {
		return *m.Platform
	}
	return RequestHeader_WIN32_X86
}

func (m *RequestHeader) GetAppInfos() *AppInfoList {
	if m != nil {
		return m.AppInfos
	}
	return nil
}

func (m *RequestHeader) GetBridgeIdentifier() string {
	if m != nil && m.BridgeIdentifier != nil {
		return *m.BridgeIdentifier
	}
	return ""
}

func (m *RequestHeader) GetBridgeVersion() *SemanticVersion {
	if m != nil {
		return m.BridgeVersion
	}
	return nil
}

func (m *RequestHeader) GetDeviceClass() RequestHeader_DeviceClass {
	if m != nil && m.DeviceClass != nil {
		return *m.DeviceClass
	}
	return RequestHeader_DESKTOP
}

type AppItem struct {
	Identifier           *string              `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
	Requirement          *AppItem_Requirement `protobuf:"varint,2,opt,name=requirement,enum=proto.AppItem_Requirement" json:"requirement,omitempty"`
	Manifest             *string              `protobuf:"bytes,4,opt,name=manifest" json:"manifest,omitempty"`
	Checksum             *string              `protobuf:"bytes,5,opt,name=checksum" json:"checksum,omitempty"`
	BundleUri            *string              `protobuf:"bytes,6,opt,name=bundle_uri,json=bundleUri" json:"bundle_uri,omitempty"`
	SmallIconUri         *string              `protobuf:"bytes,7,opt,name=small_icon_uri,json=smallIconUri" json:"small_icon_uri,omitempty"`
	LargeIconUri         *string              `protobuf:"bytes,8,opt,name=large_icon_uri,json=largeIconUri" json:"large_icon_uri,omitempty"`
	MediumIconUri        *string              `protobuf:"bytes,9,opt,name=medium_icon_uri,json=mediumIconUri" json:"medium_icon_uri,omitempty"`
	BundleType           *AppItem_Type        `protobuf:"varint,10,opt,name=bundle_type,json=bundleType,enum=proto.AppItem_Type" json:"bundle_type,omitempty"`
	Version              *SemanticVersion     `protobuf:"bytes,11,opt,name=version" json:"version,omitempty"`
	TtlInSeconds         *uint32              `protobuf:"varint,12,opt,name=ttl_in_seconds,json=ttlInSeconds" json:"ttl_in_seconds,omitempty"`
	Categories           *IdentifierList      `protobuf:"bytes,13,opt,name=categories" json:"categories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AppItem) Reset()         { *m = AppItem{} }
func (m *AppItem) String() string { return proto.CompactTextString(m) }
func (*AppItem) ProtoMessage()    {}
func (*AppItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_de00bd9912617d1d, []int{4}
}

func (m *AppItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppItem.Unmarshal(m, b)
}
func (m *AppItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppItem.Marshal(b, m, deterministic)
}
func (m *AppItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppItem.Merge(m, src)
}
func (m *AppItem) XXX_Size() int {
	return xxx_messageInfo_AppItem.Size(m)
}
func (m *AppItem) XXX_DiscardUnknown() {
	xxx_messageInfo_AppItem.DiscardUnknown(m)
}

var xxx_messageInfo_AppItem proto.InternalMessageInfo

func (m *AppItem) GetIdentifier() string {
	if m != nil && m.Identifier != nil {
		return *m.Identifier
	}
	return ""
}

func (m *AppItem) GetRequirement() AppItem_Requirement {
	if m != nil && m.Requirement != nil {
		return *m.Requirement
	}
	return AppItem_REQUIRED_INSTALL
}

func (m *AppItem) GetManifest() string {
	if m != nil && m.Manifest != nil {
		return *m.Manifest
	}
	return ""
}

func (m *AppItem) GetChecksum() string {
	if m != nil && m.Checksum != nil {
		return *m.Checksum
	}
	return ""
}

func (m *AppItem) GetBundleUri() string {
	if m != nil && m.BundleUri != nil {
		return *m.BundleUri
	}
	return ""
}

func (m *AppItem) GetSmallIconUri() string {
	if m != nil && m.SmallIconUri != nil {
		return *m.SmallIconUri
	}
	return ""
}

func (m *AppItem) GetLargeIconUri() string {
	if m != nil && m.LargeIconUri != nil {
		return *m.LargeIconUri
	}
	return ""
}

func (m *AppItem) GetMediumIconUri() string {
	if m != nil && m.MediumIconUri != nil {
		return *m.MediumIconUri
	}
	return ""
}

func (m *AppItem) GetBundleType() AppItem_Type {
	if m != nil && m.BundleType != nil {
		return *m.BundleType
	}
	return AppItem_APPLICATION
}

func (m *AppItem) GetVersion() *SemanticVersion {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *AppItem) GetTtlInSeconds() uint32 {
	if m != nil && m.TtlInSeconds != nil {
		return *m.TtlInSeconds
	}
	return 0
}

func (m *AppItem) GetCategories() *IdentifierList {
	if m != nil {
		return m.Categories
	}
	return nil
}

type AppList struct {
	Items                []*AppItem `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AppList) Reset()         { *m = AppList{} }
func (m *AppList) String() string { return proto.CompactTextString(m) }
func (*AppList) ProtoMessage()    {}
func (*AppList) Descriptor() ([]byte, []int) {
	return fileDescriptor_de00bd9912617d1d, []int{5}
}

func (m *AppList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppList.Unmarshal(m, b)
}
func (m *AppList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppList.Marshal(b, m, deterministic)
}
func (m *AppList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppList.Merge(m, src)
}
func (m *AppList) XXX_Size() int {
	return xxx_messageInfo_AppList.Size(m)
}
func (m *AppList) XXX_DiscardUnknown() {
	xxx_messageInfo_AppList.DiscardUnknown(m)
}

var xxx_messageInfo_AppList proto.InternalMessageInfo

func (m *AppList) GetItems() []*AppItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type IdentifierList struct {
	Identifiers          []string `protobuf:"bytes,1,rep,name=identifiers" json:"identifiers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdentifierList) Reset()         { *m = IdentifierList{} }
func (m *IdentifierList) String() string { return proto.CompactTextString(m) }
func (*IdentifierList) ProtoMessage()    {}
func (*IdentifierList) Descriptor() ([]byte, []int) {
	return fileDescriptor_de00bd9912617d1d, []int{6}
}

func (m *IdentifierList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdentifierList.Unmarshal(m, b)
}
func (m *IdentifierList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdentifierList.Marshal(b, m, deterministic)
}
func (m *IdentifierList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdentifierList.Merge(m, src)
}
func (m *IdentifierList) XXX_Size() int {
	return xxx_messageInfo_IdentifierList.Size(m)
}
func (m *IdentifierList) XXX_DiscardUnknown() {
	xxx_messageInfo_IdentifierList.DiscardUnknown(m)
}

var xxx_messageInfo_IdentifierList proto.InternalMessageInfo

func (m *IdentifierList) GetIdentifiers() []string {
	if m != nil {
		return m.Identifiers
	}
	return nil
}

type BannerConfig struct {
	Json                 *string  `protobuf:"bytes,1,opt,name=json" json:"json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BannerConfig) Reset()         { *m = BannerConfig{} }
func (m *BannerConfig) String() string { return proto.CompactTextString(m) }
func (*BannerConfig) ProtoMessage()    {}
func (*BannerConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_de00bd9912617d1d, []int{7}
}

func (m *BannerConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BannerConfig.Unmarshal(m, b)
}
func (m *BannerConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BannerConfig.Marshal(b, m, deterministic)
}
func (m *BannerConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BannerConfig.Merge(m, src)
}
func (m *BannerConfig) XXX_Size() int {
	return xxx_messageInfo_BannerConfig.Size(m)
}
func (m *BannerConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_BannerConfig.DiscardUnknown(m)
}

var xxx_messageInfo_BannerConfig proto.InternalMessageInfo

func (m *BannerConfig) GetJson() string {
	if m != nil && m.Json != nil {
		return *m.Json
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.RequestHeader_Platform", RequestHeader_Platform_name, RequestHeader_Platform_value)
	proto.RegisterEnum("proto.RequestHeader_DeviceClass", RequestHeader_DeviceClass_name, RequestHeader_DeviceClass_value)
	proto.RegisterEnum("proto.AppItem_Requirement", AppItem_Requirement_name, AppItem_Requirement_value)
	proto.RegisterEnum("proto.AppItem_Type", AppItem_Type_name, AppItem_Type_value)
	proto.RegisterType((*AppInfo)(nil), "proto.AppInfo")
	proto.RegisterType((*AppInfoList)(nil), "proto.AppInfoList")
	proto.RegisterType((*SemanticVersion)(nil), "proto.SemanticVersion")
	proto.RegisterType((*RequestHeader)(nil), "proto.RequestHeader")
	proto.RegisterType((*AppItem)(nil), "proto.AppItem")
	proto.RegisterType((*AppList)(nil), "proto.AppList")
	proto.RegisterType((*IdentifierList)(nil), "proto.IdentifierList")
	proto.RegisterType((*BannerConfig)(nil), "proto.BannerConfig")
}

func init() { proto.RegisterFile("appstore.proto", fileDescriptor_de00bd9912617d1d) }

var fileDescriptor_de00bd9912617d1d = []byte{
	// 970 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x95, 0xdd, 0x6e, 0xdb, 0x36,
	0x14, 0xc7, 0xeb, 0x6f, 0xfb, 0xc8, 0x76, 0x58, 0xb6, 0x0d, 0x84, 0x02, 0xdd, 0x0c, 0xa1, 0x18,
	0x02, 0x0c, 0x48, 0x0b, 0xb7, 0x0b, 0x36, 0x60, 0xbb, 0x90, 0x6d, 0x25, 0xd1, 0x22, 0x4b, 0x2a,
	0xe5, 0x34, 0xc9, 0x6e, 0x04, 0x55, 0xa6, 0x53, 0xb6, 0xd6, 0x47, 0x25, 0xba, 0x40, 0x5f, 0x61,
	0x0f, 0xb0, 0x27, 0xdd, 0xfd, 0x06, 0x92, 0x72, 0xec, 0x14, 0xc3, 0x7a, 0x65, 0x9d, 0x3f, 0x7f,
	0x3c, 0x5f, 0x3e, 0x47, 0x82, 0x61, 0x94, 0xe7, 0x25, 0xcf, 0x0a, 0x7a, 0x9c, 0x17, 0x19, 0xcf,
	0x70, 0x4b, 0xfe, 0x18, 0xbf, 0x43, 0xc7, 0xcc, 0x73, 0x3b, 0x5d, 0x65, 0xf8, 0x3b, 0x00, 0xb6,
	0xa4, 0x29, 0x67, 0x2b, 0x46, 0x0b, 0xbd, 0x36, 0xaa, 0x1d, 0xf5, 0xc8, 0x9e, 0x82, 0xbf, 0x07,
	0xed, 0x33, 0x2d, 0x4a, 0x96, 0xa5, 0x21, 0x4b, 0xb9, 0x5e, 0x1f, 0xd5, 0x8e, 0x5a, 0x04, 0x2a,
	0xc9, 0x4e, 0xb9, 0xf1, 0x0a, 0xb4, 0xca, 0x97, 0xc3, 0x4a, 0x8e, 0x9f, 0x43, 0x8b, 0x71, 0x9a,
	0x94, 0x7a, 0x6d, 0xd4, 0x38, 0xd2, 0xc6, 0x43, 0x15, 0xf8, 0xb8, 0x42, 0x88, 0x3a, 0x34, 0x02,
	0x38, 0x08, 0x68, 0x12, 0xa5, 0x9c, 0xc5, 0x6f, 0x95, 0x2b, 0xfc, 0x18, 0x5a, 0x49, 0xf4, 0x21,
	0x53, 0x39, 0xb4, 0x88, 0x32, 0xa4, 0xca, 0xd2, 0xac, 0xa8, 0x02, 0x2b, 0x43, 0xa8, 0x79, 0xc4,
	0xe3, 0xf7, 0x7a, 0x43, 0xa9, 0xd2, 0x30, 0xfe, 0x6a, 0xc3, 0x80, 0xd0, 0x4f, 0x1b, 0x5a, 0xf2,
	0x73, 0x1a, 0x2d, 0x69, 0x81, 0x0f, 0xa1, 0x9d, 0x44, 0xc5, 0x47, 0xca, 0xab, 0xc2, 0x2a, 0x0b,
	0xff, 0x02, 0xdd, 0x7c, 0x1d, 0xf1, 0x55, 0x56, 0x24, 0xd2, 0xf1, 0x70, 0xfc, 0xac, 0xca, 0xf3,
	0xde, 0xfd, 0x63, 0xbf, 0x82, 0xc8, 0x1d, 0x8e, 0x5f, 0x40, 0x2f, 0xca, 0xf3, 0x90, 0xa5, 0xab,
	0xac, 0xd4, 0xdb, 0xa3, 0xda, 0x91, 0x36, 0xc6, 0xf7, 0x6b, 0x14, 0x6d, 0x20, 0xdd, 0x48, 0x19,
	0x25, 0xfe, 0x11, 0x1e, 0xbe, 0x2b, 0xd8, 0xf2, 0x96, 0x86, 0x7b, 0x7d, 0xee, 0xc8, 0x74, 0x90,
	0x3a, 0xb0, 0x77, 0xdd, 0xfe, 0x0d, 0x86, 0x15, 0x5c, 0x75, 0x58, 0xef, 0xca, 0x10, 0x87, 0x55,
	0x88, 0xaf, 0x9a, 0x46, 0x06, 0x8a, 0xde, 0xf6, 0x70, 0x0a, 0xfd, 0x25, 0xfd, 0xcc, 0x62, 0x1a,
	0xc6, 0xeb, 0xa8, 0x2c, 0xf5, 0x9e, 0xac, 0x6d, 0xf4, 0x9f, 0xb5, 0xcd, 0x24, 0x38, 0x15, 0x1c,
	0xd1, 0x96, 0x3b, 0xc3, 0xf8, 0xb3, 0x01, 0xdd, 0x6d, 0xe1, 0x78, 0x00, 0xbd, 0x2b, 0xdb, 0x7d,
	0x35, 0x0e, 0xaf, 0x7f, 0x3e, 0x41, 0x0f, 0xb0, 0x06, 0x1d, 0x2f, 0xb8, 0x96, 0x46, 0x4d, 0x9c,
	0x39, 0xb6, 0x7b, 0xa9, 0xcc, 0x3a, 0x1e, 0x02, 0xd8, 0xfe, 0xb9, 0xe7, 0x5a, 0xa1, 0x49, 0xe6,
	0xa8, 0x81, 0x31, 0x0c, 0x83, 0x9b, 0xf9, 0xc4, 0x36, 0xdd, 0xe0, 0xe4, 0xa5, 0xd4, 0x9a, 0xf8,
	0x00, 0x34, 0x71, 0xdf, 0xf7, 0xae, 0x2c, 0xe2, 0x4f, 0x51, 0x4b, 0x08, 0xa6, 0x3b, 0x23, 0x9e,
	0x3d, 0x93, 0x44, 0xbb, 0x0a, 0x38, 0x55, 0x4e, 0x3a, 0x18, 0x41, 0xff, 0x2e, 0x46, 0x78, 0xf2,
	0x1a, 0x75, 0x45, 0x98, 0x2a, 0x05, 0x61, 0xf7, 0x70, 0x1f, 0xba, 0xbe, 0xe9, 0xcc, 0x25, 0x0f,
	0xc2, 0x52, 0x7c, 0x70, 0x8e, 0x34, 0xe1, 0xfd, 0x94, 0x58, 0xd6, 0x24, 0x98, 0xc9, 0x1c, 0xfb,
	0x22, 0xa7, 0x3d, 0x41, 0x38, 0x18, 0x08, 0x6d, 0xe2, 0x98, 0xd3, 0x8b, 0x89, 0x45, 0xc8, 0x8d,
	0x74, 0x33, 0xc4, 0x0f, 0x61, 0x10, 0x78, 0xae, 0x17, 0x84, 0x97, 0xee, 0x85, 0xeb, 0x5d, 0xb9,
	0xe8, 0x40, 0xc4, 0x55, 0x9e, 0xe7, 0xb6, 0x1f, 0x20, 0xb4, 0xab, 0x5e, 0xdc, 0x78, 0x28, 0x13,
	0xf5, 0xce, 0xec, 0x85, 0x35, 0x3d, 0x97, 0x0a, 0x16, 0x7e, 0x15, 0x20, 0xbd, 0x9f, 0xda, 0x2e,
	0x7a, 0x24, 0x2e, 0x79, 0xee, 0xc5, 0x8d, 0x27, 0x91, 0x27, 0xc2, 0xe7, 0x1b, 0xf7, 0xda, 0x5d,
	0x28, 0xfb, 0x10, 0x23, 0xd0, 0x26, 0xe6, 0xcc, 0x77, 0xcc, 0xc5, 0xa9, 0x47, 0xe6, 0xe8, 0x9f,
	0x9a, 0x31, 0x05, 0x6d, 0xef, 0x8f, 0x12, 0xfd, 0x9f, 0x59, 0xc1, 0xc5, 0xc2, 0xf3, 0x51, 0x0d,
	0x03, 0xb4, 0x17, 0xe6, 0xc4, 0xb1, 0x16, 0xa8, 0x2e, 0x9e, 0xe7, 0xde, 0xc4, 0x76, 0x2c, 0xd4,
	0xc0, 0x1d, 0x68, 0x5c, 0x59, 0x13, 0xd4, 0xc4, 0x6d, 0xa8, 0x2f, 0xde, 0xa2, 0x96, 0xf1, 0x77,
	0x53, 0xed, 0x3b, 0xa7, 0xc9, 0x37, 0xf7, 0xfd, 0x57, 0xd0, 0x0a, 0xfa, 0x69, 0xc3, 0x0a, 0x9a,
	0xd0, 0x6a, 0xdf, 0x87, 0xe3, 0xa7, 0x7b, 0x13, 0xce, 0x69, 0x22, 0x27, 0xa9, 0x22, 0xc8, 0x3e,
	0x8e, 0x9f, 0x42, 0x37, 0x89, 0x52, 0xb6, 0xa2, 0x25, 0xd7, 0x9b, 0xd2, 0xf7, 0x9d, 0x2d, 0xce,
	0xe2, 0xf7, 0x34, 0xfe, 0x58, 0x6e, 0x12, 0xbd, 0xa5, 0xce, 0xb6, 0x36, 0x7e, 0x06, 0xf0, 0x6e,
	0x93, 0x2e, 0xd7, 0x34, 0xdc, 0x14, 0x4c, 0xae, 0x55, 0x8f, 0xf4, 0x94, 0x72, 0x59, 0x30, 0xfc,
	0x1c, 0x86, 0x65, 0x12, 0xad, 0xd7, 0x21, 0x8b, 0xb3, 0x54, 0x22, 0x6a, 0x81, 0xfa, 0x52, 0xb5,
	0xe3, 0x2c, 0xad, 0xa8, 0x75, 0x54, 0x88, 0x45, 0xdb, 0x52, 0x5d, 0x45, 0x49, 0x75, 0x4b, 0xfd,
	0x00, 0x07, 0x09, 0x5d, 0xb2, 0x4d, 0xb2, 0xc3, 0x7a, 0x12, 0x1b, 0x28, 0x79, 0xcb, 0xbd, 0x06,
	0xad, 0x4a, 0x89, 0x7f, 0xc9, 0xa9, 0x0e, 0xb2, 0x11, 0x8f, 0xbe, 0x6a, 0xc4, 0xe2, 0x4b, 0x4e,
	0x49, 0x95, 0xba, 0x78, 0xc6, 0x2f, 0xa1, 0xb3, 0xdd, 0x5c, 0xed, 0x7f, 0x37, 0x77, 0x8b, 0x89,
	0xac, 0x39, 0x5f, 0x87, 0x2c, 0x0d, 0x4b, 0x1a, 0x67, 0xe9, 0xb2, 0xd4, 0xfb, 0xa3, 0xda, 0xd1,
	0x80, 0xf4, 0x39, 0x5f, 0xdb, 0x69, 0xa0, 0x34, 0xfc, 0x13, 0x40, 0x1c, 0x71, 0x7a, 0x9b, 0x15,
	0x8c, 0x96, 0xfa, 0x40, 0xba, 0x7e, 0x52, 0xb9, 0xde, 0xbd, 0x3f, 0xe4, 0xab, 0x67, 0x0f, 0x34,
	0xce, 0x40, 0xdb, 0xfb, 0xaf, 0xf0, 0x63, 0x40, 0xc4, 0x7a, 0x73, 0x69, 0x13, 0x6b, 0x16, 0xda,
	0x6e, 0xb0, 0x30, 0x1d, 0x07, 0xd5, 0xe4, 0xce, 0x98, 0x7f, 0xdc, 0x38, 0x9e, 0x39, 0x43, 0x75,
	0xc1, 0x78, 0xfe, 0xc2, 0xf6, 0x5c, 0xd3, 0xb9, 0x63, 0x1a, 0xc6, 0x18, 0x9a, 0xb2, 0x3e, 0xb1,
	0xaf, 0xbe, 0xef, 0xd8, 0x53, 0x53, 0x20, 0xe8, 0x81, 0x98, 0xe8, 0x53, 0x62, 0xce, 0xad, 0x2b,
	0x8f, 0x5c, 0xa8, 0x99, 0x9c, 0x10, 0x7b, 0x76, 0x66, 0xa1, 0xba, 0xf1, 0x42, 0x4e, 0xdd, 0xb7,
	0xbe, 0x0a, 0x9c, 0x26, 0xdb, 0xaf, 0xc2, 0x18, 0x86, 0xf7, 0x6b, 0xc1, 0x23, 0xd0, 0x76, 0xb3,
	0xa9, 0x6e, 0xf7, 0xc8, 0xbe, 0x64, 0x18, 0xd0, 0x9f, 0x44, 0x69, 0x4a, 0x8b, 0x69, 0x96, 0xae,
	0xd8, 0x2d, 0xc6, 0xd0, 0xfc, 0x50, 0x66, 0x69, 0x35, 0xd9, 0xf2, 0xf9, 0xdf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xec, 0xc6, 0xcf, 0x30, 0x06, 0x07, 0x00, 0x00,
}
