// Code generated by protoc-gen-go. DO NOT EDIT.
// source: playlist4ops.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ItemAttributesPartialState_ItemAttributeKind int32

const (
	ItemAttributesPartialState_ITEM_UNKNOWN           ItemAttributesPartialState_ItemAttributeKind = 0
	ItemAttributesPartialState_ITEM_ADDED_BY          ItemAttributesPartialState_ItemAttributeKind = 1
	ItemAttributesPartialState_ITEM_TIMESTAMP         ItemAttributesPartialState_ItemAttributeKind = 2
	ItemAttributesPartialState_ITEM_MESSAGE           ItemAttributesPartialState_ItemAttributeKind = 3
	ItemAttributesPartialState_ITEM_SEEN              ItemAttributesPartialState_ItemAttributeKind = 4
	ItemAttributesPartialState_ITEM_DOWNLOAD_COUNT    ItemAttributesPartialState_ItemAttributeKind = 5
	ItemAttributesPartialState_ITEM_DOWNLOAD_FORMAT   ItemAttributesPartialState_ItemAttributeKind = 6
	ItemAttributesPartialState_ITEM_SEVENDIGITAL_ID   ItemAttributesPartialState_ItemAttributeKind = 7
	ItemAttributesPartialState_ITEM_SEVENDIGITAL_LEFT ItemAttributesPartialState_ItemAttributeKind = 8
	ItemAttributesPartialState_ITEM_SEEN_AT           ItemAttributesPartialState_ItemAttributeKind = 9
	ItemAttributesPartialState_ITEM_PUBLIC            ItemAttributesPartialState_ItemAttributeKind = 10
)

var ItemAttributesPartialState_ItemAttributeKind_name = map[int32]string{
	0:  "ITEM_UNKNOWN",
	1:  "ITEM_ADDED_BY",
	2:  "ITEM_TIMESTAMP",
	3:  "ITEM_MESSAGE",
	4:  "ITEM_SEEN",
	5:  "ITEM_DOWNLOAD_COUNT",
	6:  "ITEM_DOWNLOAD_FORMAT",
	7:  "ITEM_SEVENDIGITAL_ID",
	8:  "ITEM_SEVENDIGITAL_LEFT",
	9:  "ITEM_SEEN_AT",
	10: "ITEM_PUBLIC",
}

var ItemAttributesPartialState_ItemAttributeKind_value = map[string]int32{
	"ITEM_UNKNOWN":           0,
	"ITEM_ADDED_BY":          1,
	"ITEM_TIMESTAMP":         2,
	"ITEM_MESSAGE":           3,
	"ITEM_SEEN":              4,
	"ITEM_DOWNLOAD_COUNT":    5,
	"ITEM_DOWNLOAD_FORMAT":   6,
	"ITEM_SEVENDIGITAL_ID":   7,
	"ITEM_SEVENDIGITAL_LEFT": 8,
	"ITEM_SEEN_AT":           9,
	"ITEM_PUBLIC":            10,
}

func (x ItemAttributesPartialState_ItemAttributeKind) Enum() *ItemAttributesPartialState_ItemAttributeKind {
	p := new(ItemAttributesPartialState_ItemAttributeKind)
	*p = x
	return p
}

func (x ItemAttributesPartialState_ItemAttributeKind) String() string {
	return proto.EnumName(ItemAttributesPartialState_ItemAttributeKind_name, int32(x))
}

func (x *ItemAttributesPartialState_ItemAttributeKind) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ItemAttributesPartialState_ItemAttributeKind_value, data, "ItemAttributesPartialState_ItemAttributeKind")
	if err != nil {
		return err
	}
	*x = ItemAttributesPartialState_ItemAttributeKind(value)
	return nil
}

func (ItemAttributesPartialState_ItemAttributeKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5dc7bfd01ffbbd65, []int{3, 0}
}

type ListAttributesPartialState_ListAttributeKind int32

const (
	ListAttributesPartialState_LIST_UNKNOWN                  ListAttributesPartialState_ListAttributeKind = 0
	ListAttributesPartialState_LIST_NAME                     ListAttributesPartialState_ListAttributeKind = 1
	ListAttributesPartialState_LIST_DESCRIPTION              ListAttributesPartialState_ListAttributeKind = 2
	ListAttributesPartialState_LIST_PICTURE                  ListAttributesPartialState_ListAttributeKind = 3
	ListAttributesPartialState_LIST_COLLABORATIVE            ListAttributesPartialState_ListAttributeKind = 4
	ListAttributesPartialState_LIST_PL3_VERSION              ListAttributesPartialState_ListAttributeKind = 5
	ListAttributesPartialState_LIST_DELETED_BY_OWNER         ListAttributesPartialState_ListAttributeKind = 6
	ListAttributesPartialState_LIST_RESTRICTED_COLLABORATIVE ListAttributesPartialState_ListAttributeKind = 7
)

var ListAttributesPartialState_ListAttributeKind_name = map[int32]string{
	0: "LIST_UNKNOWN",
	1: "LIST_NAME",
	2: "LIST_DESCRIPTION",
	3: "LIST_PICTURE",
	4: "LIST_COLLABORATIVE",
	5: "LIST_PL3_VERSION",
	6: "LIST_DELETED_BY_OWNER",
	7: "LIST_RESTRICTED_COLLABORATIVE",
}

var ListAttributesPartialState_ListAttributeKind_value = map[string]int32{
	"LIST_UNKNOWN":                  0,
	"LIST_NAME":                     1,
	"LIST_DESCRIPTION":              2,
	"LIST_PICTURE":                  3,
	"LIST_COLLABORATIVE":            4,
	"LIST_PL3_VERSION":              5,
	"LIST_DELETED_BY_OWNER":         6,
	"LIST_RESTRICTED_COLLABORATIVE": 7,
}

func (x ListAttributesPartialState_ListAttributeKind) Enum() *ListAttributesPartialState_ListAttributeKind {
	p := new(ListAttributesPartialState_ListAttributeKind)
	*p = x
	return p
}

func (x ListAttributesPartialState_ListAttributeKind) String() string {
	return proto.EnumName(ListAttributesPartialState_ListAttributeKind_name, int32(x))
}

func (x *ListAttributesPartialState_ListAttributeKind) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ListAttributesPartialState_ListAttributeKind_value, data, "ListAttributesPartialState_ListAttributeKind")
	if err != nil {
		return err
	}
	*x = ListAttributesPartialState_ListAttributeKind(value)
	return nil
}

func (ListAttributesPartialState_ListAttributeKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5dc7bfd01ffbbd65, []int{4, 0}
}

type Op_Kind int32

const (
	Op_KIND_UNKNOWN           Op_Kind = 0
	Op_ADD                    Op_Kind = 2
	Op_REM                    Op_Kind = 3
	Op_MOV                    Op_Kind = 4
	Op_UPDATE_ITEM_ATTRIBUTES Op_Kind = 5
	Op_UPDATE_LIST_ATTRIBUTES Op_Kind = 6
)

var Op_Kind_name = map[int32]string{
	0: "KIND_UNKNOWN",
	2: "ADD",
	3: "REM",
	4: "MOV",
	5: "UPDATE_ITEM_ATTRIBUTES",
	6: "UPDATE_LIST_ATTRIBUTES",
}

var Op_Kind_value = map[string]int32{
	"KIND_UNKNOWN":           0,
	"ADD":                    2,
	"REM":                    3,
	"MOV":                    4,
	"UPDATE_ITEM_ATTRIBUTES": 5,
	"UPDATE_LIST_ATTRIBUTES": 6,
}

func (x Op_Kind) Enum() *Op_Kind {
	p := new(Op_Kind)
	*p = x
	return p
}

func (x Op_Kind) String() string {
	return proto.EnumName(Op_Kind_name, int32(x))
}

func (x *Op_Kind) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Op_Kind_value, data, "Op_Kind")
	if err != nil {
		return err
	}
	*x = Op_Kind(value)
	return nil
}

func (Op_Kind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5dc7bfd01ffbbd65, []int{7, 0}
}

type Add struct {
	FromIndex            *int32        `protobuf:"varint,1,opt,name=fromIndex" json:"fromIndex,omitempty"`
	Items                []*Item       `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
	ListChecksum         *ListChecksum `protobuf:"bytes,3,opt,name=list_checksum,json=listChecksum" json:"list_checksum,omitempty"`
	AddLast              *bool         `protobuf:"varint,4,opt,name=addLast" json:"addLast,omitempty"`
	AddFirst             *bool         `protobuf:"varint,5,opt,name=addFirst" json:"addFirst,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Add) Reset()         { *m = Add{} }
func (m *Add) String() string { return proto.CompactTextString(m) }
func (*Add) ProtoMessage()    {}
func (*Add) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dc7bfd01ffbbd65, []int{0}
}

func (m *Add) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Add.Unmarshal(m, b)
}
func (m *Add) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Add.Marshal(b, m, deterministic)
}
func (m *Add) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Add.Merge(m, src)
}
func (m *Add) XXX_Size() int {
	return xxx_messageInfo_Add.Size(m)
}
func (m *Add) XXX_DiscardUnknown() {
	xxx_messageInfo_Add.DiscardUnknown(m)
}

var xxx_messageInfo_Add proto.InternalMessageInfo

func (m *Add) GetFromIndex() int32 {
	if m != nil && m.FromIndex != nil {
		return *m.FromIndex
	}
	return 0
}

func (m *Add) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Add) GetListChecksum() *ListChecksum {
	if m != nil {
		return m.ListChecksum
	}
	return nil
}

func (m *Add) GetAddLast() bool {
	if m != nil && m.AddLast != nil {
		return *m.AddLast
	}
	return false
}

func (m *Add) GetAddFirst() bool {
	if m != nil && m.AddFirst != nil {
		return *m.AddFirst
	}
	return false
}

type Rem struct {
	FromIndex            *int32        `protobuf:"varint,1,opt,name=fromIndex" json:"fromIndex,omitempty"`
	Length               *int32        `protobuf:"varint,2,opt,name=length" json:"length,omitempty"`
	Items                []*Item       `protobuf:"bytes,3,rep,name=items" json:"items,omitempty"`
	ListChecksum         *ListChecksum `protobuf:"bytes,4,opt,name=list_checksum,json=listChecksum" json:"list_checksum,omitempty"`
	ItemsChecksum        *ListChecksum `protobuf:"bytes,5,opt,name=items_checksum,json=itemsChecksum" json:"items_checksum,omitempty"`
	UrisChecksum         *ListChecksum `protobuf:"bytes,6,opt,name=uris_checksum,json=urisChecksum" json:"uris_checksum,omitempty"`
	ItemsAsKey           *bool         `protobuf:"varint,7,opt,name=itemsAsKey" json:"itemsAsKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Rem) Reset()         { *m = Rem{} }
func (m *Rem) String() string { return proto.CompactTextString(m) }
func (*Rem) ProtoMessage()    {}
func (*Rem) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dc7bfd01ffbbd65, []int{1}
}

func (m *Rem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rem.Unmarshal(m, b)
}
func (m *Rem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rem.Marshal(b, m, deterministic)
}
func (m *Rem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rem.Merge(m, src)
}
func (m *Rem) XXX_Size() int {
	return xxx_messageInfo_Rem.Size(m)
}
func (m *Rem) XXX_DiscardUnknown() {
	xxx_messageInfo_Rem.DiscardUnknown(m)
}

var xxx_messageInfo_Rem proto.InternalMessageInfo

func (m *Rem) GetFromIndex() int32 {
	if m != nil && m.FromIndex != nil {
		return *m.FromIndex
	}
	return 0
}

func (m *Rem) GetLength() int32 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

func (m *Rem) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Rem) GetListChecksum() *ListChecksum {
	if m != nil {
		return m.ListChecksum
	}
	return nil
}

func (m *Rem) GetItemsChecksum() *ListChecksum {
	if m != nil {
		return m.ItemsChecksum
	}
	return nil
}

func (m *Rem) GetUrisChecksum() *ListChecksum {
	if m != nil {
		return m.UrisChecksum
	}
	return nil
}

func (m *Rem) GetItemsAsKey() bool {
	if m != nil && m.ItemsAsKey != nil {
		return *m.ItemsAsKey
	}
	return false
}

type Mov struct {
	FromIndex            *int32        `protobuf:"varint,1,opt,name=fromIndex" json:"fromIndex,omitempty"`
	Length               *int32        `protobuf:"varint,2,opt,name=length" json:"length,omitempty"`
	ToIndex              *int32        `protobuf:"varint,3,opt,name=toIndex" json:"toIndex,omitempty"`
	ListChecksum         *ListChecksum `protobuf:"bytes,4,opt,name=list_checksum,json=listChecksum" json:"list_checksum,omitempty"`
	ItemsChecksum        *ListChecksum `protobuf:"bytes,5,opt,name=items_checksum,json=itemsChecksum" json:"items_checksum,omitempty"`
	UrisChecksum         *ListChecksum `protobuf:"bytes,6,opt,name=uris_checksum,json=urisChecksum" json:"uris_checksum,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Mov) Reset()         { *m = Mov{} }
func (m *Mov) String() string { return proto.CompactTextString(m) }
func (*Mov) ProtoMessage()    {}
func (*Mov) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dc7bfd01ffbbd65, []int{2}
}

func (m *Mov) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mov.Unmarshal(m, b)
}
func (m *Mov) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mov.Marshal(b, m, deterministic)
}
func (m *Mov) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mov.Merge(m, src)
}
func (m *Mov) XXX_Size() int {
	return xxx_messageInfo_Mov.Size(m)
}
func (m *Mov) XXX_DiscardUnknown() {
	xxx_messageInfo_Mov.DiscardUnknown(m)
}

var xxx_messageInfo_Mov proto.InternalMessageInfo

func (m *Mov) GetFromIndex() int32 {
	if m != nil && m.FromIndex != nil {
		return *m.FromIndex
	}
	return 0
}

func (m *Mov) GetLength() int32 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

func (m *Mov) GetToIndex() int32 {
	if m != nil && m.ToIndex != nil {
		return *m.ToIndex
	}
	return 0
}

func (m *Mov) GetListChecksum() *ListChecksum {
	if m != nil {
		return m.ListChecksum
	}
	return nil
}

func (m *Mov) GetItemsChecksum() *ListChecksum {
	if m != nil {
		return m.ItemsChecksum
	}
	return nil
}

func (m *Mov) GetUrisChecksum() *ListChecksum {
	if m != nil {
		return m.UrisChecksum
	}
	return nil
}

type ItemAttributesPartialState struct {
	Values               *ItemAttributes                                `protobuf:"bytes,1,opt,name=values" json:"values,omitempty"`
	NoValue              []ItemAttributesPartialState_ItemAttributeKind `protobuf:"varint,2,rep,name=no_value,json=noValue,enum=proto.ItemAttributesPartialState_ItemAttributeKind" json:"no_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                       `json:"-"`
	XXX_unrecognized     []byte                                         `json:"-"`
	XXX_sizecache        int32                                          `json:"-"`
}

func (m *ItemAttributesPartialState) Reset()         { *m = ItemAttributesPartialState{} }
func (m *ItemAttributesPartialState) String() string { return proto.CompactTextString(m) }
func (*ItemAttributesPartialState) ProtoMessage()    {}
func (*ItemAttributesPartialState) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dc7bfd01ffbbd65, []int{3}
}

func (m *ItemAttributesPartialState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemAttributesPartialState.Unmarshal(m, b)
}
func (m *ItemAttributesPartialState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemAttributesPartialState.Marshal(b, m, deterministic)
}
func (m *ItemAttributesPartialState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemAttributesPartialState.Merge(m, src)
}
func (m *ItemAttributesPartialState) XXX_Size() int {
	return xxx_messageInfo_ItemAttributesPartialState.Size(m)
}
func (m *ItemAttributesPartialState) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemAttributesPartialState.DiscardUnknown(m)
}

var xxx_messageInfo_ItemAttributesPartialState proto.InternalMessageInfo

func (m *ItemAttributesPartialState) GetValues() *ItemAttributes {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *ItemAttributesPartialState) GetNoValue() []ItemAttributesPartialState_ItemAttributeKind {
	if m != nil {
		return m.NoValue
	}
	return nil
}

type ListAttributesPartialState struct {
	Values               *ListAttributes                                `protobuf:"bytes,1,opt,name=values" json:"values,omitempty"`
	NoValue              []ListAttributesPartialState_ListAttributeKind `protobuf:"varint,2,rep,name=no_value,json=noValue,enum=proto.ListAttributesPartialState_ListAttributeKind" json:"no_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                       `json:"-"`
	XXX_unrecognized     []byte                                         `json:"-"`
	XXX_sizecache        int32                                          `json:"-"`
}

func (m *ListAttributesPartialState) Reset()         { *m = ListAttributesPartialState{} }
func (m *ListAttributesPartialState) String() string { return proto.CompactTextString(m) }
func (*ListAttributesPartialState) ProtoMessage()    {}
func (*ListAttributesPartialState) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dc7bfd01ffbbd65, []int{4}
}

func (m *ListAttributesPartialState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAttributesPartialState.Unmarshal(m, b)
}
func (m *ListAttributesPartialState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAttributesPartialState.Marshal(b, m, deterministic)
}
func (m *ListAttributesPartialState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAttributesPartialState.Merge(m, src)
}
func (m *ListAttributesPartialState) XXX_Size() int {
	return xxx_messageInfo_ListAttributesPartialState.Size(m)
}
func (m *ListAttributesPartialState) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAttributesPartialState.DiscardUnknown(m)
}

var xxx_messageInfo_ListAttributesPartialState proto.InternalMessageInfo

func (m *ListAttributesPartialState) GetValues() *ListAttributes {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *ListAttributesPartialState) GetNoValue() []ListAttributesPartialState_ListAttributeKind {
	if m != nil {
		return m.NoValue
	}
	return nil
}

type UpdateItemAttributes struct {
	Index                 *int32                      `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	NewAttributes         *ItemAttributesPartialState `protobuf:"bytes,2,opt,name=new_attributes,json=newAttributes" json:"new_attributes,omitempty"`
	OldAttributes         *ItemAttributesPartialState `protobuf:"bytes,3,opt,name=old_attributes,json=oldAttributes" json:"old_attributes,omitempty"`
	ListChecksum          *ListChecksum               `protobuf:"bytes,4,opt,name=list_checksum,json=listChecksum" json:"list_checksum,omitempty"`
	OldAttributesChecksum *ListChecksum               `protobuf:"bytes,5,opt,name=old_attributes_checksum,json=oldAttributesChecksum" json:"old_attributes_checksum,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                    `json:"-"`
	XXX_unrecognized      []byte                      `json:"-"`
	XXX_sizecache         int32                       `json:"-"`
}

func (m *UpdateItemAttributes) Reset()         { *m = UpdateItemAttributes{} }
func (m *UpdateItemAttributes) String() string { return proto.CompactTextString(m) }
func (*UpdateItemAttributes) ProtoMessage()    {}
func (*UpdateItemAttributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dc7bfd01ffbbd65, []int{5}
}

func (m *UpdateItemAttributes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateItemAttributes.Unmarshal(m, b)
}
func (m *UpdateItemAttributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateItemAttributes.Marshal(b, m, deterministic)
}
func (m *UpdateItemAttributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateItemAttributes.Merge(m, src)
}
func (m *UpdateItemAttributes) XXX_Size() int {
	return xxx_messageInfo_UpdateItemAttributes.Size(m)
}
func (m *UpdateItemAttributes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateItemAttributes.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateItemAttributes proto.InternalMessageInfo

func (m *UpdateItemAttributes) GetIndex() int32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *UpdateItemAttributes) GetNewAttributes() *ItemAttributesPartialState {
	if m != nil {
		return m.NewAttributes
	}
	return nil
}

func (m *UpdateItemAttributes) GetOldAttributes() *ItemAttributesPartialState {
	if m != nil {
		return m.OldAttributes
	}
	return nil
}

func (m *UpdateItemAttributes) GetListChecksum() *ListChecksum {
	if m != nil {
		return m.ListChecksum
	}
	return nil
}

func (m *UpdateItemAttributes) GetOldAttributesChecksum() *ListChecksum {
	if m != nil {
		return m.OldAttributesChecksum
	}
	return nil
}

type UpdateListAttributes struct {
	NewAttributes         *ListAttributesPartialState `protobuf:"bytes,1,opt,name=new_attributes,json=newAttributes" json:"new_attributes,omitempty"`
	OldAttributes         *ListAttributesPartialState `protobuf:"bytes,2,opt,name=old_attributes,json=oldAttributes" json:"old_attributes,omitempty"`
	ListChecksum          *ListChecksum               `protobuf:"bytes,3,opt,name=list_checksum,json=listChecksum" json:"list_checksum,omitempty"`
	OldAttributesChecksum *ListChecksum               `protobuf:"bytes,4,opt,name=old_attributes_checksum,json=oldAttributesChecksum" json:"old_attributes_checksum,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                    `json:"-"`
	XXX_unrecognized      []byte                      `json:"-"`
	XXX_sizecache         int32                       `json:"-"`
}

func (m *UpdateListAttributes) Reset()         { *m = UpdateListAttributes{} }
func (m *UpdateListAttributes) String() string { return proto.CompactTextString(m) }
func (*UpdateListAttributes) ProtoMessage()    {}
func (*UpdateListAttributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dc7bfd01ffbbd65, []int{6}
}

func (m *UpdateListAttributes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateListAttributes.Unmarshal(m, b)
}
func (m *UpdateListAttributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateListAttributes.Marshal(b, m, deterministic)
}
func (m *UpdateListAttributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateListAttributes.Merge(m, src)
}
func (m *UpdateListAttributes) XXX_Size() int {
	return xxx_messageInfo_UpdateListAttributes.Size(m)
}
func (m *UpdateListAttributes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateListAttributes.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateListAttributes proto.InternalMessageInfo

func (m *UpdateListAttributes) GetNewAttributes() *ListAttributesPartialState {
	if m != nil {
		return m.NewAttributes
	}
	return nil
}

func (m *UpdateListAttributes) GetOldAttributes() *ListAttributesPartialState {
	if m != nil {
		return m.OldAttributes
	}
	return nil
}

func (m *UpdateListAttributes) GetListChecksum() *ListChecksum {
	if m != nil {
		return m.ListChecksum
	}
	return nil
}

func (m *UpdateListAttributes) GetOldAttributesChecksum() *ListChecksum {
	if m != nil {
		return m.OldAttributesChecksum
	}
	return nil
}

type Op struct {
	Kind                 *Op_Kind              `protobuf:"varint,1,opt,name=kind,enum=proto.Op_Kind" json:"kind,omitempty"`
	Add                  *Add                  `protobuf:"bytes,2,opt,name=add" json:"add,omitempty"`
	Rem                  *Rem                  `protobuf:"bytes,3,opt,name=rem" json:"rem,omitempty"`
	Mov                  *Mov                  `protobuf:"bytes,4,opt,name=mov" json:"mov,omitempty"`
	UpdateItemAttributes *UpdateItemAttributes `protobuf:"bytes,5,opt,name=update_item_attributes,json=updateItemAttributes" json:"update_item_attributes,omitempty"`
	UpdateListAttributes *UpdateListAttributes `protobuf:"bytes,6,opt,name=update_list_attributes,json=updateListAttributes" json:"update_list_attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Op) Reset()         { *m = Op{} }
func (m *Op) String() string { return proto.CompactTextString(m) }
func (*Op) ProtoMessage()    {}
func (*Op) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dc7bfd01ffbbd65, []int{7}
}

func (m *Op) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Op.Unmarshal(m, b)
}
func (m *Op) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Op.Marshal(b, m, deterministic)
}
func (m *Op) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Op.Merge(m, src)
}
func (m *Op) XXX_Size() int {
	return xxx_messageInfo_Op.Size(m)
}
func (m *Op) XXX_DiscardUnknown() {
	xxx_messageInfo_Op.DiscardUnknown(m)
}

var xxx_messageInfo_Op proto.InternalMessageInfo

func (m *Op) GetKind() Op_Kind {
	if m != nil && m.Kind != nil {
		return *m.Kind
	}
	return Op_KIND_UNKNOWN
}

func (m *Op) GetAdd() *Add {
	if m != nil {
		return m.Add
	}
	return nil
}

func (m *Op) GetRem() *Rem {
	if m != nil {
		return m.Rem
	}
	return nil
}

func (m *Op) GetMov() *Mov {
	if m != nil {
		return m.Mov
	}
	return nil
}

func (m *Op) GetUpdateItemAttributes() *UpdateItemAttributes {
	if m != nil {
		return m.UpdateItemAttributes
	}
	return nil
}

func (m *Op) GetUpdateListAttributes() *UpdateListAttributes {
	if m != nil {
		return m.UpdateListAttributes
	}
	return nil
}

type OpList struct {
	Ops                  []*Op    `protobuf:"bytes,1,rep,name=ops" json:"ops,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpList) Reset()         { *m = OpList{} }
func (m *OpList) String() string { return proto.CompactTextString(m) }
func (*OpList) ProtoMessage()    {}
func (*OpList) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dc7bfd01ffbbd65, []int{8}
}

func (m *OpList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpList.Unmarshal(m, b)
}
func (m *OpList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpList.Marshal(b, m, deterministic)
}
func (m *OpList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpList.Merge(m, src)
}
func (m *OpList) XXX_Size() int {
	return xxx_messageInfo_OpList.Size(m)
}
func (m *OpList) XXX_DiscardUnknown() {
	xxx_messageInfo_OpList.DiscardUnknown(m)
}

var xxx_messageInfo_OpList proto.InternalMessageInfo

func (m *OpList) GetOps() []*Op {
	if m != nil {
		return m.Ops
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.ItemAttributesPartialState_ItemAttributeKind", ItemAttributesPartialState_ItemAttributeKind_name, ItemAttributesPartialState_ItemAttributeKind_value)
	proto.RegisterEnum("proto.ListAttributesPartialState_ListAttributeKind", ListAttributesPartialState_ListAttributeKind_name, ListAttributesPartialState_ListAttributeKind_value)
	proto.RegisterEnum("proto.Op_Kind", Op_Kind_name, Op_Kind_value)
	proto.RegisterType((*Add)(nil), "proto.Add")
	proto.RegisterType((*Rem)(nil), "proto.Rem")
	proto.RegisterType((*Mov)(nil), "proto.Mov")
	proto.RegisterType((*ItemAttributesPartialState)(nil), "proto.ItemAttributesPartialState")
	proto.RegisterType((*ListAttributesPartialState)(nil), "proto.ListAttributesPartialState")
	proto.RegisterType((*UpdateItemAttributes)(nil), "proto.UpdateItemAttributes")
	proto.RegisterType((*UpdateListAttributes)(nil), "proto.UpdateListAttributes")
	proto.RegisterType((*Op)(nil), "proto.Op")
	proto.RegisterType((*OpList)(nil), "proto.OpList")
}

func init() { proto.RegisterFile("playlist4ops.proto", fileDescriptor_5dc7bfd01ffbbd65) }

var fileDescriptor_5dc7bfd01ffbbd65 = []byte{
	// 944 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x56, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xc6, 0x76, 0x7e, 0xda, 0x93, 0x4d, 0x98, 0x4e, 0xd3, 0xac, 0xc9, 0x2e, 0xa8, 0xb5, 0x84,
	0xd4, 0x1b, 0x7a, 0x91, 0xe5, 0x62, 0xc5, 0x9d, 0x1b, 0x4f, 0x77, 0xad, 0xf8, 0x27, 0x8c, 0x9d,
	0x54, 0x5c, 0x59, 0xa6, 0x36, 0xac, 0xd5, 0xc4, 0x8e, 0x62, 0xa7, 0xcb, 0x3e, 0x00, 0x8f, 0x80,
	0x78, 0x0b, 0x24, 0x6e, 0x78, 0x05, 0x78, 0x12, 0xde, 0x81, 0x3b, 0x34, 0x13, 0xc7, 0xb1, 0x69,
	0x4a, 0xb3, 0x2b, 0x6e, 0xb8, 0x6a, 0xce, 0xf7, 0xcd, 0xf7, 0xcd, 0xcc, 0x39, 0x67, 0x8e, 0x0b,
	0x78, 0x31, 0xf3, 0xdf, 0xcd, 0xa2, 0x34, 0xfb, 0x32, 0x59, 0xa4, 0x17, 0x8b, 0x65, 0x92, 0x25,
	0xb8, 0xce, 0xff, 0xf4, 0x8f, 0x0b, 0x6a, 0x1e, 0x66, 0xfe, 0x9a, 0xeb, 0xf7, 0x0a, 0xf0, 0x26,
	0x89, 0xb3, 0x30, 0xce, 0xd6, 0xb8, 0xf2, 0x9b, 0x00, 0x92, 0x1a, 0x04, 0xf8, 0x39, 0x1c, 0x7e,
	0xb7, 0x4c, 0xe6, 0x7a, 0x1c, 0x84, 0x3f, 0xc8, 0xc2, 0xa9, 0x70, 0x5e, 0xa7, 0x5b, 0x00, 0x9f,
	0x41, 0x3d, 0xca, 0xc2, 0x79, 0x2a, 0x8b, 0xa7, 0xd2, 0x79, 0x6b, 0xd0, 0x5a, 0x8b, 0x2f, 0xf4,
	0x2c, 0x9c, 0xd3, 0x35, 0x83, 0x5f, 0x42, 0x9b, 0xd9, 0x7b, 0x37, 0x6f, 0xc2, 0x9b, 0xdb, 0x74,
	0x35, 0x97, 0xa5, 0x53, 0xe1, 0xbc, 0x35, 0x38, 0xce, 0x97, 0x1a, 0x51, 0x9a, 0x0d, 0x73, 0x8a,
	0x3e, 0x99, 0x95, 0x22, 0x2c, 0x43, 0xd3, 0x0f, 0x02, 0xc3, 0x4f, 0x33, 0xb9, 0x76, 0x2a, 0x9c,
	0x1f, 0xd0, 0x4d, 0x88, 0xfb, 0x70, 0xe0, 0x07, 0xc1, 0x55, 0xb4, 0x4c, 0x33, 0xb9, 0xce, 0xa9,
	0x22, 0x56, 0x7e, 0x11, 0x41, 0xa2, 0xe1, 0xfc, 0x91, 0x83, 0xf7, 0xa0, 0x31, 0x0b, 0xe3, 0xef,
	0xb3, 0x37, 0xb2, 0xc8, 0xa9, 0x3c, 0xda, 0x5e, 0x48, 0xda, 0xff, 0x42, 0xb5, 0x7d, 0x2f, 0xf4,
	0x15, 0x74, 0xb8, 0xc5, 0x56, 0x5a, 0x7f, 0x58, 0xda, 0xe6, 0x4b, 0x0b, 0xed, 0x4b, 0x68, 0xaf,
	0x96, 0x51, 0x49, 0xda, 0xf8, 0x97, 0x5d, 0xd9, 0xca, 0x42, 0xf9, 0x19, 0x00, 0xb7, 0x52, 0xd3,
	0x51, 0xf8, 0x4e, 0x6e, 0xf2, 0x74, 0x95, 0x10, 0xe5, 0x47, 0x11, 0x24, 0x33, 0xb9, 0xfb, 0xc0,
	0x84, 0xc9, 0xd0, 0xcc, 0x92, 0xb5, 0x46, 0xe2, 0xc4, 0x26, 0xfc, 0xbf, 0xe5, 0x49, 0xf9, 0x59,
	0x82, 0x3e, 0xab, 0xb3, 0x9a, 0x65, 0xcb, 0xe8, 0xdb, 0x55, 0x16, 0xa6, 0x63, 0x7f, 0x99, 0x45,
	0xfe, 0xcc, 0xc9, 0xfc, 0x2c, 0xc4, 0x5f, 0x40, 0xe3, 0xce, 0x9f, 0xad, 0xc2, 0x94, 0xe7, 0xa6,
	0x35, 0x38, 0x29, 0xb5, 0xc6, 0x56, 0x42, 0xf3, 0x45, 0xd8, 0x82, 0x83, 0x38, 0xf1, 0x78, 0xc0,
	0x1f, 0x47, 0x67, 0xf0, 0x62, 0xa7, 0xa0, 0xbc, 0x47, 0x95, 0x1a, 0x45, 0x71, 0x40, 0x9b, 0x71,
	0x32, 0x65, 0x1e, 0xca, 0x5f, 0x02, 0x1c, 0xdd, 0xa3, 0x31, 0x82, 0x27, 0xba, 0x4b, 0x4c, 0x6f,
	0x62, 0x8d, 0x2c, 0xfb, 0xda, 0x42, 0x1f, 0xe1, 0x23, 0x68, 0x73, 0x44, 0xd5, 0x34, 0xa2, 0x79,
	0x97, 0xdf, 0x20, 0x01, 0x63, 0xe8, 0x70, 0xc8, 0xd5, 0x4d, 0xe2, 0xb8, 0xaa, 0x39, 0x46, 0x62,
	0x21, 0x34, 0x89, 0xe3, 0xa8, 0xaf, 0x08, 0x92, 0x70, 0x1b, 0x0e, 0x39, 0xe2, 0x10, 0x62, 0xa1,
	0x1a, 0x7e, 0x0a, 0xc7, 0x3c, 0xd4, 0xec, 0x6b, 0xcb, 0xb0, 0x55, 0xcd, 0x1b, 0xda, 0x13, 0xcb,
	0x45, 0x75, 0x2c, 0x43, 0xb7, 0x4a, 0x5c, 0xd9, 0xd4, 0x54, 0x5d, 0xd4, 0x28, 0x18, 0x87, 0x4c,
	0x89, 0xa5, 0xe9, 0xaf, 0x74, 0x57, 0x35, 0x3c, 0x5d, 0x43, 0x4d, 0xdc, 0x87, 0xde, 0x7d, 0xc6,
	0x20, 0x57, 0x2e, 0x3a, 0x28, 0x4e, 0xc2, 0xf6, 0xf5, 0x54, 0x17, 0x1d, 0xe2, 0x8f, 0xa1, 0xc5,
	0x91, 0xf1, 0xe4, 0xd2, 0xd0, 0x87, 0x08, 0x94, 0x3f, 0x45, 0xe8, 0xb3, 0xc2, 0xbd, 0x67, 0x65,
	0xaa, 0x92, 0x3d, 0x2a, 0xf3, 0xf0, 0x1e, 0x55, 0xaa, 0x5a, 0x99, 0x3f, 0x04, 0x38, 0xba, 0x47,
	0xb3, 0x6b, 0x19, 0xba, 0xe3, 0x96, 0x2a, 0xd3, 0x86, 0x43, 0x8e, 0x58, 0xaa, 0x49, 0x90, 0x80,
	0xbb, 0x80, 0x78, 0xa8, 0x11, 0x67, 0x48, 0xf5, 0xb1, 0xab, 0xdb, 0xd6, 0xba, 0x2e, 0x1c, 0x1d,
	0xeb, 0x43, 0x77, 0x42, 0x59, 0x5d, 0x7a, 0x80, 0x39, 0x32, 0xb4, 0x0d, 0x43, 0xbd, 0xb4, 0xa9,
	0xea, 0xea, 0x53, 0x82, 0x6a, 0x85, 0x7e, 0x6c, 0xbc, 0xf0, 0xa6, 0x84, 0x3a, 0x4c, 0x5f, 0xc7,
	0x9f, 0xc0, 0x49, 0xee, 0x6a, 0x10, 0x97, 0x37, 0x80, 0x67, 0x5f, 0x5b, 0x84, 0xa2, 0x06, 0x3e,
	0x83, 0x4f, 0x39, 0x45, 0x89, 0xe3, 0x52, 0x7d, 0xc8, 0xd8, 0xaa, 0x67, 0x53, 0xf9, 0x5d, 0x84,
	0xee, 0x64, 0x11, 0xf8, 0x59, 0x58, 0x6d, 0x52, 0xdc, 0x85, 0x7a, 0x54, 0x9a, 0x0b, 0xeb, 0x00,
	0xbf, 0x86, 0x4e, 0x1c, 0xbe, 0xf5, 0xfc, 0x62, 0x1d, 0x9f, 0x0d, 0xad, 0xc1, 0xd9, 0xa3, 0x9d,
	0x4e, 0xdb, 0x71, 0xf8, 0xb6, 0xe4, 0xff, 0x1a, 0x3a, 0xc9, 0x2c, 0x28, 0x3b, 0x49, 0x7b, 0x3b,
	0x25, 0xb3, 0xa0, 0xe4, 0xf4, 0xe1, 0x53, 0x67, 0x04, 0x4f, 0xab, 0x67, 0xd8, 0x6b, 0xfc, 0x9c,
	0x54, 0xb6, 0x2f, 0x86, 0xc9, 0xaf, 0x45, 0x26, 0xab, 0x4d, 0xb5, 0x23, 0x67, 0x42, 0xe5, 0xa6,
	0x0f, 0xf7, 0xe0, 0xe3, 0x39, 0x13, 0xf7, 0x76, 0x7a, 0x24, 0x67, 0xd2, 0x7f, 0x90, 0xb3, 0xda,
	0x7b, 0xe7, 0xec, 0x27, 0x09, 0x44, 0x7b, 0x81, 0x15, 0xa8, 0xdd, 0x46, 0x71, 0xc0, 0xf3, 0xd2,
	0x19, 0x74, 0x72, 0x03, 0x7b, 0x71, 0xc1, 0x9f, 0x1d, 0xe7, 0xf0, 0x73, 0x90, 0xfc, 0x20, 0xc8,
	0x2f, 0x0c, 0xf9, 0x12, 0x35, 0x08, 0x28, 0x83, 0x19, 0xbb, 0x0c, 0x37, 0xb7, 0xd8, 0xb0, 0x34,
	0x9c, 0x53, 0x06, 0x33, 0x76, 0x9e, 0xdc, 0xe5, 0xe7, 0xdb, 0xb0, 0x66, 0x72, 0x47, 0x19, 0x8c,
	0xbf, 0x86, 0xde, 0x8a, 0xd7, 0xcd, 0x63, 0xdf, 0x95, 0x72, 0x76, 0xd7, 0x4d, 0xf0, 0x2c, 0x17,
	0xec, 0x7a, 0x26, 0xb4, 0xbb, 0xda, 0xf5, 0x78, 0xb6, 0x96, 0x3c, 0xcb, 0x25, 0xcb, 0xc6, 0x0e,
	0xcb, 0x7f, 0x4c, 0xad, 0xdc, 0xb2, 0x8a, 0x2a, 0xb7, 0x50, 0xdb, 0x4c, 0x99, 0x91, 0x6e, 0x69,
	0xa5, 0x29, 0xd3, 0x04, 0x49, 0xd5, 0x34, 0x24, 0xb2, 0x1f, 0x94, 0x98, 0x48, 0x62, 0x3f, 0x4c,
	0x7b, 0x8a, 0x6a, 0x6c, 0x0a, 0x4f, 0xc6, 0x9a, 0xea, 0x12, 0x6f, 0xfd, 0x85, 0x70, 0x5d, 0xaa,
	0x5f, 0x4e, 0x5c, 0xe2, 0xa0, 0x7a, 0x89, 0xe3, 0x33, 0xa2, 0xc4, 0x35, 0x94, 0xcf, 0xa1, 0x61,
	0x2f, 0xd8, 0x01, 0xf0, 0x33, 0x90, 0x92, 0x05, 0xeb, 0x58, 0xf6, 0xbf, 0xd1, 0x61, 0x51, 0x19,
	0xca, 0xd0, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xb2, 0xa9, 0xa2, 0x97, 0x7a, 0x0a, 0x00, 0x00,
}
