// Code generated by protoc-gen-go. DO NOT EDIT.
// source: popcount.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PopcountRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PopcountRequest) Reset()         { *m = PopcountRequest{} }
func (m *PopcountRequest) String() string { return proto.CompactTextString(m) }
func (*PopcountRequest) ProtoMessage()    {}
func (*PopcountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c780a13a015fc54, []int{0}
}

func (m *PopcountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PopcountRequest.Unmarshal(m, b)
}
func (m *PopcountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PopcountRequest.Marshal(b, m, deterministic)
}
func (m *PopcountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PopcountRequest.Merge(m, src)
}
func (m *PopcountRequest) XXX_Size() int {
	return xxx_messageInfo_PopcountRequest.Size(m)
}
func (m *PopcountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PopcountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PopcountRequest proto.InternalMessageInfo

type PopcountResult struct {
	Count                  *int64   `protobuf:"zigzag64,1,opt,name=count" json:"count,omitempty"`
	Truncated              *bool    `protobuf:"varint,2,opt,name=truncated" json:"truncated,omitempty"`
	User                   []string `protobuf:"bytes,3,rep,name=user" json:"user,omitempty"`
	SubscriptionTimestamps []int64  `protobuf:"zigzag64,4,rep,name=subscriptionTimestamps" json:"subscriptionTimestamps,omitempty"`
	InsertionTimestamps    []int64  `protobuf:"zigzag64,5,rep,name=insertionTimestamps" json:"insertionTimestamps,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *PopcountResult) Reset()         { *m = PopcountResult{} }
func (m *PopcountResult) String() string { return proto.CompactTextString(m) }
func (*PopcountResult) ProtoMessage()    {}
func (*PopcountResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c780a13a015fc54, []int{1}
}

func (m *PopcountResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PopcountResult.Unmarshal(m, b)
}
func (m *PopcountResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PopcountResult.Marshal(b, m, deterministic)
}
func (m *PopcountResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PopcountResult.Merge(m, src)
}
func (m *PopcountResult) XXX_Size() int {
	return xxx_messageInfo_PopcountResult.Size(m)
}
func (m *PopcountResult) XXX_DiscardUnknown() {
	xxx_messageInfo_PopcountResult.DiscardUnknown(m)
}

var xxx_messageInfo_PopcountResult proto.InternalMessageInfo

func (m *PopcountResult) GetCount() int64 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *PopcountResult) GetTruncated() bool {
	if m != nil && m.Truncated != nil {
		return *m.Truncated
	}
	return false
}

func (m *PopcountResult) GetUser() []string {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *PopcountResult) GetSubscriptionTimestamps() []int64 {
	if m != nil {
		return m.SubscriptionTimestamps
	}
	return nil
}

func (m *PopcountResult) GetInsertionTimestamps() []int64 {
	if m != nil {
		return m.InsertionTimestamps
	}
	return nil
}

func init() {
	proto.RegisterType((*PopcountRequest)(nil), "proto.PopcountRequest")
	proto.RegisterType((*PopcountResult)(nil), "proto.PopcountResult")
}

func init() { proto.RegisterFile("popcount.proto", fileDescriptor_2c780a13a015fc54) }

var fileDescriptor_2c780a13a015fc54 = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8b, 0xb1, 0x0a, 0xc2, 0x30,
	0x10, 0x86, 0x89, 0x6d, 0xc1, 0xde, 0x50, 0xf1, 0x14, 0xc9, 0xe0, 0x10, 0x3a, 0x65, 0x12, 0x27,
	0x9f, 0x43, 0x82, 0x2f, 0x50, 0x6b, 0x86, 0x80, 0x4d, 0x62, 0xee, 0xf2, 0x82, 0x3e, 0x99, 0x10,
	0x85, 0x82, 0xe8, 0x74, 0xf7, 0x7f, 0x1f, 0x1f, 0x74, 0x31, 0xc4, 0x31, 0x64, 0xcf, 0x87, 0x98,
	0x02, 0x07, 0x6c, 0xca, 0xe9, 0xd7, 0xb0, 0x3a, 0x7f, 0x84, 0xb1, 0x8f, 0x6c, 0x89, 0xfb, 0xa7,
	0x80, 0x6e, 0x66, 0x94, 0xef, 0x8c, 0x5b, 0x68, 0xca, 0x94, 0x42, 0x09, 0x8d, 0xe6, 0x3d, 0x70,
	0x0f, 0x2d, 0xa7, 0xec, 0xc7, 0x81, 0xed, 0x4d, 0x2e, 0x94, 0xd0, 0x4b, 0x33, 0x03, 0x44, 0xa8,
	0x33, 0xd9, 0x24, 0x2b, 0x55, 0xe9, 0xd6, 0x94, 0x1f, 0x4f, 0xb0, 0xa3, 0x7c, 0xa5, 0x31, 0xb9,
	0xc8, 0x2e, 0xf8, 0x8b, 0x9b, 0x2c, 0xf1, 0x30, 0x45, 0x92, 0xb5, 0xaa, 0x34, 0x9a, 0x3f, 0x16,
	0x8f, 0xb0, 0x71, 0x9e, 0x6c, 0xfa, 0x8a, 0x9a, 0x12, 0xfd, 0x52, 0xaf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xc5, 0x32, 0xdb, 0x11, 0xef, 0x00, 0x00, 0x00,
}
