// Code generated by protoc-gen-go. DO NOT EDIT.
// source: toplist.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Toplist struct {
	Items                []string `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Toplist) Reset()         { *m = Toplist{} }
func (m *Toplist) String() string { return proto.CompactTextString(m) }
func (*Toplist) ProtoMessage()    {}
func (*Toplist) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e538c167b0732f2, []int{0}
}

func (m *Toplist) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Toplist.Unmarshal(m, b)
}
func (m *Toplist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Toplist.Marshal(b, m, deterministic)
}
func (m *Toplist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Toplist.Merge(m, src)
}
func (m *Toplist) XXX_Size() int {
	return xxx_messageInfo_Toplist.Size(m)
}
func (m *Toplist) XXX_DiscardUnknown() {
	xxx_messageInfo_Toplist.DiscardUnknown(m)
}

var xxx_messageInfo_Toplist proto.InternalMessageInfo

func (m *Toplist) GetItems() []string {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*Toplist)(nil), "proto.Toplist")
}

func init() { proto.RegisterFile("toplist.proto", fileDescriptor_6e538c167b0732f2) }

var fileDescriptor_6e538c167b0732f2 = []byte{
	// 67 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0xc9, 0x2f, 0xc8,
	0xc9, 0x2c, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xf2, 0x5c,
	0xec, 0x21, 0x10, 0x71, 0x21, 0x11, 0x2e, 0xd6, 0xcc, 0x92, 0xd4, 0xdc, 0x62, 0x09, 0x46, 0x05,
	0x66, 0x0d, 0xce, 0x20, 0x08, 0x07, 0x10, 0x00, 0x00, 0xff, 0xff, 0x46, 0x5e, 0x9d, 0x2c, 0x37,
	0x00, 0x00, 0x00,
}
